language: node_js
nvm:

matrix:
  include:
  - node_js: "4"
    script: npm run test4
  - node_js: "6"
    script: npm run test4
  - node_js: "8"
    script: npm run test10
  - node_js: "10"
    script: npm run test10
